### PR TITLE
Add ability to specify custom offset value for hidden image/html | cl…

### PR DESCRIPTION
**Pull request by andrewhl**
…oses #48

### CODE REVIEW

**Comment by cameronhimself** [comment]
Thanks for this. I wonder, though, is there a reason this can't simply be done with styling? I'm not sure it needs to be prop.

**Comment by andrewhl** [comment]
I found the issue. It occurs when using bootstrap-vue's `card-group` component with a prop of `columns`. I don't know why exactly, but changing it to `deck` caused the hidden card to disappear. I think columns does something to the height of its element, so that it loops within the element rather than moving beyond it.

I think you can safely ignore this PR.

**Comment by cameronhimself** [comment]
👍 Thanks for taking the time regardless!

**Comment by andrewhl** [comment]
Actually, I'd like to reconsider closing this.

Upon further inspection, I'm still getting the issue, even with the `deck` option:

screen shot 2018-06-10 at 16 09 42

I've tried targeting the element, unsuccessfully. I've tried targeting the child element (here with the .flip-card class), but it affects the element that is being dragged, which isn't what I want. If I modify the property `top: -1000px` to `-2000px` in the code inspector, I get the result I want. I can't seem to control this value any other way.

**Comment by andrewhl** [comment]
Actually, found another solution using `overflow: hidden`. This DnD stuff sure is finicky!

**Pull request closed without merging**
